In [3]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import h5py
import os

In [85]:
def norm_w_mask(x,mask, threshold):
    x_out = np.zeros_like(x, dtype=np.float64)
    mask =mask.astype(bool)
#     print x.shape,mask.shape
    for ii in range(x.shape[0]):
        k=np.median(x[ii][mask[ii]])
        mu = np.std(x[ii][mask[ii]])
        this_mask = (np.abs(x[ii] - k)<mu*threshold)*mask[ii]
        x_out[ii] = (x[ii]-(x[ii][this_mask]).mean())* this_mask
    return x_out

def diff_all_shots(images,mask,threshold):
    images = norm_all_shots(images, mask, threshold)
    diffs = images - images.mean(0)[None,:]
    
    return diffs, images

def norm_all_shots(images,mask, threshold):
    norms = np.zeros_like(images, dtype=np.float64)
    for ii in range(norms.shape[0]):
        norms[ii]=norm_w_mask(images[ii],mask, threshold)
    return norms

In [86]:
data_dir = '/reg/d/psdm/cxi/cxilr6716/scratch/combined_tables/cali_gai/'
run_num =111

run_file = "run%d.tbl"%run_num
f = h5py.File(os.path.join(data_dir, run_file), 'r')

PI = f['polar_imgs'][:100]
shot_tage_to_keep=np.array(range(100))

In [87]:
mask = np.array(f['polar_mask_binned'].value==f['polar_mask_binned'].value.max(), dtype = int)

In [90]:
qidx = 15
outlier_threshold=1000
shots=PI[:,qidx,:][shot_tage_to_keep,None,:]
this_mask = mask[qidx][None,:]
norm_shots = norm_all_shots(shots.astype(np.float64),this_mask, outlier_threshold)

In [91]:
norm_shots.mean(-1)

array([[  2.23188884e-13],
       [ -3.57102214e-13],
       [  6.69566652e-14],
       [  8.92755535e-13],
       [ -3.57102214e-13],
       [  5.35653321e-13],
       [  2.45507772e-13],
       [ -5.13334433e-13],
       [  8.92755535e-14],
       [ -1.33913330e-13],
       [ -4.46377768e-14],
       [  1.78551107e-13],
       [  8.25798870e-13],
       [ -6.69566652e-13],
       [ -1.18290108e-12],
       [ -8.92755535e-14],
       [ -6.69566652e-13],
       [ -6.24928875e-13],
       [  1.33913330e-12],
       [ -1.02666887e-12],
       [ -2.67826661e-13],
       [ -1.54000330e-12],
       [  1.42840886e-12],
       [ -1.33913330e-13],
       [ -2.00869995e-13],
       [  7.14204428e-13],
       [  8.92755535e-14],
       [  9.82031089e-13],
       [  9.82031089e-13],
       [  8.92755535e-14],
       [  1.16058220e-12],
       [ -8.92755535e-14],
       [  1.38377108e-12],
       [ -6.91885540e-13],
       [  7.14204428e-13],
       [  4.91015545e-13],
       [ -2.23188884e-13],
 

In [84]:
x = (shots[0]).astype(np.float64)
y =x[0]-x[0][this_mask[0]==1].mean() 
z = y*this_mask[0]
print z[this_mask[0]==1].sum()
print z[this_mask[0]==0].sum()
# x_out = np.zeros_like(x, dtype=np.float64)
# #     print x.shape,mask.shape
#     for ii in range(x.shape[0]):
#         k=np.median(x[ii][mask[ii]])
#         mu = np.std(x[ii][mask[ii]])
#         this_mask = (np.abs(x[ii] - k)<mu*threshold)*mask[ii]
#         x_out[ii] = (x[ii]-(x[ii][this_mask]).mean())* this_mask

1.09139364213e-10
0.0


In [77]:
z[this_mask[0]==0]

array([-0.,  0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,  0.,
        0., -0., -0.,  0.,  0., -0., -0., -0., -0., -0., -0., -0., -0.,
       -0., -0., -0., -0., -0., -0.,  0., -0.,  0., -0., -0., -0., -0.,
       -0., -0.,  0.,  0., -0., -0., -0., -0., -0., -0., -0., -0.,  0.,
        0.,  0.,  0.,  0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
       -0., -0.])

In [80]:
this_mask

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
        1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 